defaults: &defaults
  working_directory: /tmp/turtl/desktop
  docker:
    - image: circleci/node:4.8.3

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p config && cp config.live.js config/config.js

      # install our apt deps
      - run: sudo apt-get update
      - run: sudo apt-get install --fix-missing rsync gpgv2 libgpg-error0 libgpg-error-dev libgcrypt20-dev

      # install libsodium
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz -O /tmp/libsodium.tar.gz
      - run: wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.15.tar.gz.sig -O /tmp/libsodium.tar.gz.sig

      # verify sodium
      - run: gpg --import scripts/libsodium.gpg.pub
      - run: gpg --verify /tmp/libsodium.tar.gz.sig /tmp/libsodium.tar.gz
      - restore_cache:
          key: sodium-v2-{{ checksum "/tmp/libsodium.tar.gz" }}
      - run: cd /tmp && tar -xvf ./libsodium.tar.gz && cd libsodium-1.0.15 && ./configure && make
      - save_cache:
          key: sodium-v2-{{ checksum "/tmp/libsodium.tar.gz" }}
          paths:
            - /tmp/libsodium-1.0.15
      - run: cd /tmp/libsodium-1.0.15 && sudo make install

      # install rust
      - run: wget https://static.rust-lang.org/rustup.sh -O /tmp/rustup.sh && chmod 0750 /tmp/rustup.sh
      - run: sudo /tmp/rustup.sh --revision=1.21.0

      # grab core
      - run: git clone https://github.com/turtl/core-rs ../core
      - run: find ../core -name "*.rs" | grep -v target | sort | xargs sha256sum > ../SHA256.core-rs

      # grab js
      - run: git clone https://github.com/turtl/js ../js
      - run: find ../js -name "*.js" | grep -v node_modules | sort | xargs sha256sum > ../SHA256.js
      - restore_cache:
          key: js-npm-v2-{{ checksum "../js/package.json" }}
          key: js-npm-v2-
      - run: cd ../js && npm install
      - save_cache:
          key: js-npm-v2-{{ checksum "../js/package.json" }}
          paths:
            - ../js/node_modules

      # build desktop
      - restore_cache:
          key: npm-v2-{{ .Branch }}-{{ checksum "package.json" }}
          key: npm-v2-{{ .Branch }}-
      - run: npm install
      - save_cache:
          key: npm-v2-{{ checksum "package.json" }}
          paths:
            - node_modules
      - restore_cache:
          key: desktop-build-v3-{{ .Branch }}-{{ checksum "../SHA256.core-rs" }}-{{ checksum "../SHA256.js" }}
      - run: make
      - persist_to_workspace:
          root: /tmp/turtl
          paths:
            - desktop

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/turtl
      - run: make test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build

